{{ if .Values.ingress.enabled }}
{{- $defaultServiceName := include "standard-app.v1.default-service-name" . -}}
{{- $serviceName := default $defaultServiceName .Values.service.name -}}
{{- $servicePort := .Values.service.port -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "util.v1.autoname" . }}-http
  namespace: {{ .Values.Namespace }}
  labels:
    app.kubernetes.io/managed-by: nhds-helm-chart
{{ include "standard-app.v1.resource-labels" . | indent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-sandbox
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    {{- end }}
{{ with .Values.ingress.extraAnnotations }}{{ toYaml . | indent 4 }}{{ end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.defaultBackend.enabled }}
  - pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
    backend:
      service:
        name: {{ .Values.service.name }}
        port:
          number: {{ $servicePort }}
{{- end }}
  rules:
  - host: {{ required ".Values.ingress.host must be specified when .Values.ingress.enabled is true" .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.path | default "/" | quote }}
        pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ $servicePort }}
{{- range .Values.ingress.extraHosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
      - path: /
        pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
      - backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ $servicePort }}
{{- end }}
  tls:
    - hosts:
        - {{ required ".Values.ingress.host must be specified when .Values.ingress.enabled is true" .Values.ingress.host | quote }}
      secretName: {{ .Values.service.name }}
{{ end }}
