{{- if .Values.secrets.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: {{ .Values.secrets.secretType }}
data:
{{- range $name, $value := .Values.secretKeys }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc | quote }}
{{- end}}
{{- end }}
{{- end }}